CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clients (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE INVOICE_STATUS AS ENUM ('PENDING', 'APPROVED', 'CANCELED');

CREATE TABLE IF NOT EXISTS invoices (
  id SERIAL NOT NULL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  client_id BIGINT NOT NULL REFERENCES clients (id) ON UPDATE CASCADE ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  status INVOICE_STATUS NOT NULL DEFAULT 'PENDING',
  total_amount NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
  users ("name")
VALUES
  ('John Doe');

INSERT INTO
  clients ("name")
VALUES
  ('Google');